name: Zaki One Click Deploy
on:
  workflow_dispatch:
    inputs:
      project_id:
        description: 'ضع هنا رقم المختبر'
        required: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # هذه الأداة هي التي ستحل لغز المصادقة
      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: 'Deploy'
        run: |
          gcloud config set project ${{ github.event.inputs.project_id }}
          gcloud run deploy zaki-server --source . --region europe-west1 --allow-unauthenticated --port 8080 --quiet
          
          echo "🚀 مبروك يا زكي! هذا هو رابطك السحري:"
          gcloud run services describe zaki-server --region europe-west1 --format='value(status.url)'
